### ISSUE TITLE
freeDrawing mode doesn't work when it's your first choice

### ISSUE THREAD

**Issue by Turajek** [lionix-team/vue-image-markup-demo#2]
**When it works:**
 I click first other icon ( for example rect or circle option ) and then I choose freeDrawing option.
**When it doesn't work:**
I don't click any other option before and I click freeDrawing option. Console throws error:
![image](https://user-images.githubusercontent.com/42206167/79454805-2354f080-7fec-11ea-9a16-fe761192c88f.png)
I think the problem is in this line:
![image](https://user-images.githubusercontent.com/42206167/79455111-a6764680-7fec-11ea-9435-c514c2bdf9fa.png)

**Comment by lilitsimonyan98** [comment]
The issue has been resolved.
