### ISSUE TITLE
Default fontStyle value doesn't work in text mode

### ISSUE THREAD

**Issue by Turajek** [lionix-team/vue-image-markup-demo#3]
Using setTool('text') without declaring params results in error: 
![image](https://user-images.githubusercontent.com/42206167/79456071-2650e080-7fee-11ea-8876-cd1f6523d194.png)
![image](https://user-images.githubusercontent.com/42206167/79456099-310b7580-7fee-11ea-9e7e-1c4eedc9a226.png)
When I change it to setTool('text', {fontStyle: 'normal'}) then it works properly

**Comment by lilitsimonyan98** [comment]
The issue has been resolved.
